name: Auto Deploy 🚀

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 📤
        uses: actions/checkout@v3

      - name: Install sshpass 🛠️
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy files via SCP 📡
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -P 8288 -r . arunikaprawira@103.82.240.20:/var/www/vhosts/arunikaprawira.com/httpdocs/app.arunikaprawira.com/

      - name: ✅ Deployment Success
        run: echo "Deployment completed successfully!"