name: Auto Deploy 🚀

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 📤
        uses: actions/checkout@v3

      - name: Deploy files via SCP 📡
        run: |
          scp -i /var/www/vhosts/arunikaprawira.com/.ssh/deploy_key.pem -r * arunikaprawira@103.82.240.20:httpdocs/app.arunikaprawira.com/

      - name: ✅ Deployment Success
        run: echo "Deployment completed successfully!"
